name: acolhimento_digital
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  firebase_core: ^1.2.0
  flutter_launcher_icons: ^0.9.0
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.22.0
  google_maps_flutter: ^2.0.5
  injectable: ^1.4.0
  intl: ^0.17.0
  map_launcher: ^2.0.0
  mobx: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  platform_device_id: ^1.0.1
  smooth_page_indicator: ^0.3.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.2
  hive_generator: ^1.1.0
  injectable_generator: ^1.4.0
  mobx_codegen: ^2.0.1+3
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
